class ErrorCode:
    SUCCESS = "SUCCESS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PROCESSING_ERROR = "PROCESSING_ERROR"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    TIMEOUT = "TIMEOUT"
    DOCUMENT_LIMIT = "DOCUMENT_LIMIT"
    EMPTY_DOCUMENT = "EMPTY_DOCUMENT"
